apiVersion: v1
kind: Namespace
metadata:
  name: phoenix-system-2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phoenix-app-code-v2
  namespace: phoenix-system-2
data:
  main.py: |
    from fastapi import FastAPI
    import time
    app = FastAPI()
    @app.get("/")
    async def root():
        return {"message": "MISSION ACCOMPLISHED: PHOENIX GATEKEEPER IS ONLINE"}
    @app.get("/health")
    async def health():
        return {"status": "ok"}
---
apiVersion: v1
kind: Service
metadata:
  name: phoenix-service
  namespace: phoenix-system-2
spec:
  type: LoadBalancer
  selector:
    app: phoenix-gatekeeper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix-deployment
  namespace: phoenix-system-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phoenix-gatekeeper
  template:
    metadata:
      labels:
        app: phoenix-gatekeeper
    strategy:
      type: Recreate 
    spec:
      initContainers:
      - name: init-check-db
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup google.com; do echo 'WAITING FOR DB...'; sleep 2; done"]
      containers:
      - name: phoenix-server
        image: python:3.11-slim
        workingDir: /app
        command: ["/bin/sh", "-c"]
        args: ["pip install fastapi uvicorn && uvicorn main:app --host 0.0.0.0 --port 8000"]
        ports:
        - containerPort: 8000
        startupProbe:
          exec:
            command: ["verify-payload.sh"]
          failureThreshold: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 1
          periodSeconds: 2
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          successThreshold: 10
          periodSeconds: 5
