apiVersion: v1
kind: Namespace
metadata:
  name: phoenix-system-2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phoenix-app-code-v2
  namespace: phoenix-system-2
data:
  main.py: |
    from fastapi import FastAPI
    import time
    app = FastAPI()
    @app.get("/")
    async def root():
        return {"message": "MISSION ACCOMPLISHED: PHOENIX GATEKEEPER IS ONLINE"}
    @app.get("/health")
    async def health():
        return {"status": "ok"}
---
# THE VICTORY BEACON (No Errors)
apiVersion: v1
kind: Service
metadata:
  name: phoenix-service
  namespace: phoenix-system-2
spec:
  type: LoadBalancer
  selector:
    app: phoenix-gatekeeper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix-deployment
  namespace: phoenix-system-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phoenix-gatekeeper
  template:
    metadata:
      labels:
        app: phoenix-gatekeeper
    strategy:
      type: Recreate 
    spec:
      # --- STAGE 1: THE INIT BARRIER ---
      initContainers:
      - name: init-check-db
        image: busybox:1.28
        # ERROR 1: DEPENDENCY DEADLOCK
        # Logic: Stuck at 'Init:0/1' waiting for a ghost service.
        # FIX: Change 'db-backend-prod' to 'google.com' or remove this block.
        command: ['sh', '-c', "until nslookup db-backend-prod; do echo 'WAITING FOR DB...'; sleep 2; done"]

      containers:
      - name: phoenix-server
        image: python:3.11-slim
        workingDir: /app
        command: ["/bin/sh", "-c"]
        args: ["pip install fastapi uvicorn && uvicorn main:app --host 0.0.0.0 --port 8000"]
        ports:
        - containerPort: 8000
        
        # --- STAGE 2: STARTUP PROTOCOL ---
        # ERROR 2: OCI RUNTIME EXECUTION FAILURE
        # Logic: Startup probe fails because the script doesn't exist.
        # FIX: Change command to ["ls", "main.py"] or remove the probe.
        startupProbe:
          exec:
            command: ["verify-payload.sh"]
          failureThreshold: 30
          periodSeconds: 5

        # --- STAGE 3: THE LIVENESS LOOP ---
        # ERROR 3: THE IMPATIENT RESTART
        # Logic: Killing the pod before 'pip install' and 'uvicorn' finish.
        # FIX: Increase initialDelaySeconds to 30.
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 1
          periodSeconds: 2

        # --- STAGE 4: THE READINESS GATE ---
        # ERROR 4: THE TARGET MISMATCH
        # Logic: Checking port 8080 (Nothing there) instead of 8000.
        # FIX: Change port to 8000.
        # ERROR 5: THE CONFIDENCE OVERLOAD
        # Logic: Pod is fine, but waiting for 10 consecutive passes (50 seconds).
        # FIX: Set successThreshold to 1.
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          successThreshold: 10
          periodSeconds: 5
